//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klinik.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingService
    {
        public int id { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> ClinicPoliID { get; set; }
        public Nullable<int> DoctorScheduleID { get; set; }
        public Nullable<System.DateTime> ServiceDate { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<int> Counter { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<short> RowStatus { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string LastUpdateBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    }
}
