//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klinik.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clinic
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string LegalNumber { get; set; }
        public Nullable<System.DateTime> LegalDate { get; set; }
        public string ContactNumber { get; set; }
        public string Email { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Long { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<short> ClinicType { get; set; }
        public Nullable<int> ReffID { get; set; }
        public Nullable<short> RowStatus { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string LastUpdateBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    }
}
