//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klinik.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_Klinik_2Entities : DbContext
    {
        public DB_Klinik_2Entities()
            : base("name=DB_Klinik_2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADM_Menu> ADM_Menu { get; set; }
        public virtual DbSet<ADM_ModuleAuthorization> ADM_ModuleAuthorization { get; set; }
        public virtual DbSet<ADM_Role> ADM_Role { get; set; }
        public virtual DbSet<ADM_UserPassword> ADM_UserPassword { get; set; }
        public virtual DbSet<ADM_UserRole> ADM_UserRole { get; set; }
        public virtual DbSet<BookingService> BookingServices { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Clinic> Clinics { get; set; }
        public virtual DbSet<ClinicPoli> ClinicPolis { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<DoctorAbsentSchedule> DoctorAbsentSchedules { get; set; }
        public virtual DbSet<DoctorSchedule> DoctorSchedules { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Parameter> Parameters { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<PatientToEmp> PatientToEmps { get; set; }
        public virtual DbSet<Poli> Polis { get; set; }
    }
}
