//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klinik.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public long ID { get; set; }
        public string MRNumber { get; set; }
        public string Name { get; set; }
        public Nullable<long> EmpID { get; set; }
        public string IdentityNumber { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string BirthCity { get; set; }
        public Nullable<short> MarriageStatus { get; set; }
        public string Address { get; set; }
        public Nullable<int> CityID { get; set; }
        public string HPNumber { get; set; }
        public string Gender { get; set; }
        public string BloodType { get; set; }
        public string ReshusType { get; set; }
        public Nullable<short> Religion { get; set; }
        public string ContactName { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<short> ContactType { get; set; }
        public string ContactAddress { get; set; }
        public Nullable<short> RowStatus { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string LastUpdateBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    }
}
