//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klinik.Data.DataRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Doctors = new HashSet<Doctor>();
            this.EmployeeAssignments = new HashSet<EmployeeAssignment>();
            this.Patients = new HashSet<Patient>();
            this.Users = new HashSet<User>();
        }
    
        public long ID { get; set; }
        public string EmpID { get; set; }
        public string EmpName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string ReffEmpID { get; set; }
        public string Gender { get; set; }
        public Nullable<short> EmpType { get; set; }
        public string KTPNumber { get; set; }
        public string HPNumber { get; set; }
        public string Email { get; set; }
        public string LastEmpID { get; set; }
        public Nullable<short> Status { get; set; }
        public short RowStatus { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doctor> Doctors { get; set; }
        public virtual EmployeeStatu EmployeeStatu { get; set; }
        public virtual FamilyRelationship FamilyRelationship { get; set; }
        public virtual GeneralMaster GeneralMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeAssignment> EmployeeAssignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patient> Patients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
