//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klinik.Data.DataRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormExamineLab
    {
        public long ID { get; set; }
        public Nullable<long> FormMedicalID { get; set; }
        public string LabType { get; set; }
        public Nullable<int> LabItemID { get; set; }
        public string Result { get; set; }
        public string ResultIndicator { get; set; }
        public Nullable<short> RowStatus { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual FormMedical FormMedical { get; set; }
        public virtual LabItem LabItem { get; set; }
    }
}
