//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klinik.Data.DataRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueuePoli
    {
        public long ID { get; set; }
        public long ClinicID { get; set; }
        public long PatientID { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<long> FormMedicalID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public short Type { get; set; }
        public Nullable<long> AppointmentID { get; set; }
        public int SortNumber { get; set; }
        public int PoliFrom { get; set; }
        public int PoliTo { get; set; }
        public string Remark { get; set; }
        public Nullable<long> ReffID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsPreExamine { get; set; }
        public short RowStatus { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Clinic Clinic { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual FormMedical FormMedical { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Poli Poli { get; set; }
        public virtual Poli Poli1 { get; set; }
    }
}
