//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klinik.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Klinik.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0} Failed.
        /// </summary>
        public static string AddObjectFailed {
            get {
                return ResourceManager.GetString("AddObjectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be changed for non-active user.
        /// </summary>
        public static string CannotChangePasswordForInactiveUser {
            get {
                return ResourceManager.GetString("CannotChangePasswordForInactiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Successfully Saved.
        /// </summary>
        public static string DataSaved {
            get {
                return ResourceManager.GetString("DataSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Successfully Updated.
        /// </summary>
        public static string DataUpdated {
            get {
                return ResourceManager.GetString("DataUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        public static string Doctor {
            get {
                return ResourceManager.GetString("Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi,
        ///
        ///We got request for reset your account password. Please click on the below link to reset your password 
        ///&lt;a href= {0} &gt;Reset Password link&lt;/a&gt;
        ///
        ///Regards,
        ///
        ///Administrator.
        /// </summary>
        public static string EmailBodyResetPassword {
            get {
                return ResourceManager.GetString("EmailBodyResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee with an email {0} does not exist.
        /// </summary>
        public static string EmployeeWithEmailNotExist {
            get {
                return ResourceManager.GetString("EmployeeWithEmailNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops.. Something went wrong. Please check the Error Log or Contact customer support.
        /// </summary>
        public static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Photo File.
        /// </summary>
        public static string InvalidImage {
            get {
                return ResourceManager.GetString("InvalidImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Model State. Please check your input..
        /// </summary>
        public static string InvalidModelState {
            get {
                return ResourceManager.GetString("InvalidModelState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Organization Code.
        /// </summary>
        public static string InvalidOrganizationCode {
            get {
                return ResourceManager.GetString("InvalidOrganizationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Reset Password Code .
        /// </summary>
        public static string InvalidResetPasswordCode {
            get {
                return ResourceManager.GetString("InvalidResetPasswordCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User Name or Password.
        /// </summary>
        public static string InvalidUsernamePassword {
            get {
                return ResourceManager.GetString("InvalidUsernamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menstrual and KB Date is only for woman. Don&apos;t fill if patient is a men.
        /// </summary>
        public static string MenstrualDataProhibited {
            get {
                return ResourceManager.GetString("MenstrualDataProhibited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} with ID {2} has been successfully added.
        /// </summary>
        public static string ObjectHasBeenAdded {
            get {
                return ResourceManager.GetString("ObjectHasBeenAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} with ID {1} has been successfully added.
        /// </summary>
        public static string ObjectHasBeenAdded2 {
            get {
                return ResourceManager.GetString("ObjectHasBeenAdded2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} with ID {2} has been successfully removed.
        /// </summary>
        public static string ObjectHasBeenRemoved {
            get {
                return ResourceManager.GetString("ObjectHasBeenRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} with ID {1} has been successfully removed.
        /// </summary>
        public static string ObjectHasBeenRemoved2 {
            get {
                return ResourceManager.GetString("ObjectHasBeenRemoved2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} with ID {2} has been successfully updated.
        /// </summary>
        public static string ObjectHasBeenUpdated {
            get {
                return ResourceManager.GetString("ObjectHasBeenUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} with ID {1} has been successfully updated.
        /// </summary>
        public static string ObjectHasBeenUpdated2 {
            get {
                return ResourceManager.GetString("ObjectHasBeenUpdated2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient with name {0} has been Added for clinic Id {1}.
        /// </summary>
        public static string ObjectPatientAdded {
            get {
                return ResourceManager.GetString("ObjectPatientAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient with name  {0} has been Updated for clinic Id {1}.
        /// </summary>
        public static string ObjectPatientUpdated {
            get {
                return ResourceManager.GetString("ObjectPatientUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre Examine Data for Patient {0} has been added with Id {1}.
        /// </summary>
        public static string ObjectPreExamineDataAdded {
            get {
                return ResourceManager.GetString("ObjectPreExamineDataAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One employee cannot have more than one user Id.
        /// </summary>
        public static string OneEmpOneUserID {
            get {
                return ResourceManager.GetString("OneEmpOneUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramedic.
        /// </summary>
        public static string Paramedic {
            get {
                return ResourceManager.GetString("Paramedic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password already used in the past, please use another.
        /// </summary>
        public static string PasswordHasBeenUsedBefore {
            get {
                return ResourceManager.GetString("PasswordHasBeenUsedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        public static string Patient {
            get {
                return ResourceManager.GetString("Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient is not registered in Poli yet.
        /// </summary>
        public static string PatientNotRegistered {
            get {
                return ResourceManager.GetString("PatientNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove {0} Failed.
        /// </summary>
        public static string RemoveObjectFailed {
            get {
                return ResourceManager.GetString("RemoveObjectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following Fields must be filled : {0}.
        /// </summary>
        public static string RequiredFieldsMissing {
            get {
                return ResourceManager.GetString("RequiredFieldsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password link has been sent to your email address..
        /// </summary>
        public static string ResetPasswordLinkSent {
            get {
                return ResourceManager.GetString("ResetPasswordLinkSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Expired.
        /// </summary>
        public static string SessionExpired {
            get {
                return ResourceManager.GetString("SessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STRValidTo should be greater than STRValidFrom.
        /// </summary>
        public static string STRValidToInvalid {
            get {
                return ResourceManager.GetString("STRValidToInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized Access!.
        /// </summary>
        public static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee {0} is not recognized.
        /// </summary>
        public static string UnrecognizedEmployee {
            get {
                return ResourceManager.GetString("UnrecognizedEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be changed because user name and password not match.
        /// </summary>
        public static string UpdateFailedUsernamePasswordNotMatch {
            get {
                return ResourceManager.GetString("UpdateFailedUsernamePasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update {0} Failed.
        /// </summary>
        public static string UpdateObjectFailed {
            get {
                return ResourceManager.GetString("UpdateObjectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization of this user does not have clinic, please assign clinic to this user.
        /// </summary>
        public static string UserDoesNotHaveClinic {
            get {
                return ResourceManager.GetString("UserDoesNotHaveClinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name already exist.
        /// </summary>
        public static string UsernameAlreadyExist {
            get {
                return ResourceManager.GetString("UsernameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Not Found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User password has been successfully updated.
        /// </summary>
        public static string UserPasswordUpdated {
            get {
                return ResourceManager.GetString("UserPasswordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed update user password.
        /// </summary>
        public static string UserPasswordUpdateFailed {
            get {
                return ResourceManager.GetString("UserPasswordUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Error for following fields : {0}.
        /// </summary>
        public static string ValidationErrorFields {
            get {
                return ResourceManager.GetString("ValidationErrorFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following fields are not recognized : {0}.
        /// </summary>
        public static string ValidationUnrecognizedFields {
            get {
                return ResourceManager.GetString("ValidationUnrecognizedFields", resourceCulture);
            }
        }
    }
}
