//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klinik.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Klinik.Resources.UIMessages", typeof(UIMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Info.
        /// </summary>
        public static string AccountInfo {
            get {
                return ResourceManager.GetString("AccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktif.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to the terms of service.
        /// </summary>
        public static string Agreement {
            get {
                return ResourceManager.GetString("Agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Pre Examine.
        /// </summary>
        public static string AlreadyPreExamine {
            get {
                return ResourceManager.GetString("AlreadyPreExamine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string AnErrorOccured {
            get {
                return ResourceManager.GetString("AnErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Role.
        /// </summary>
        public static string AssignRole {
            get {
                return ResourceManager.GetString("AssignRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To Home.
        /// </summary>
        public static string BackToHome {
            get {
                return ResourceManager.GetString("BackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdate.
        /// </summary>
        public static string Birthdate {
            get {
                return ResourceManager.GetString("Birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Type.
        /// </summary>
        public static string BloodType {
            get {
                return ResourceManager.GetString("BloodType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPJS No.
        /// </summary>
        public static string BPJSNo {
            get {
                return ResourceManager.GetString("BPJSNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Unit.
        /// </summary>
        public static string BusinessUnit {
            get {
                return ResourceManager.GetString("BusinessUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic.
        /// </summary>
        public static string Clinic {
            get {
                return ResourceManager.GetString("Clinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic Code.
        /// </summary>
        public static string ClinicCode {
            get {
                return ResourceManager.GetString("ClinicCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic List.
        /// </summary>
        public static string ClinicList {
            get {
                return ResourceManager.GetString("ClinicList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic Name.
        /// </summary>
        public static string ClinicName {
            get {
                return ResourceManager.GetString("ClinicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic Type.
        /// </summary>
        public static string ClinicType {
            get {
                return ResourceManager.GetString("ClinicType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Blind.
        /// </summary>
        public static string ColorBlind {
            get {
                return ResourceManager.GetString("ColorBlind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        public static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Logs.
        /// </summary>
        public static string CommandLog {
            get {
                return ResourceManager.GetString("CommandLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact No.
        /// </summary>
        public static string ContactNo {
            get {
                return ResourceManager.GetString("ContactNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright 2019. Medical Management System. All rights reserved..
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Address.
        /// </summary>
        public static string CurrentAddress {
            get {
                return ResourceManager.GetString("CurrentAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Glasses.
        /// </summary>
        public static string DailyGlasses {
            get {
                return ResourceManager.GetString("DailyGlasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this data ( ID : .
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diastolic.
        /// </summary>
        public static string Diastolic {
            get {
                return ResourceManager.GetString("Diastolic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        public static string Doctor {
            get {
                return ResourceManager.GetString("Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor Info.
        /// </summary>
        public static string DoctorInfo {
            get {
                return ResourceManager.GetString("DoctorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor List.
        /// </summary>
        public static string DoctorList {
            get {
                return ResourceManager.GetString("DoctorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor Name.
        /// </summary>
        public static string DoctorName {
            get {
                return ResourceManager.GetString("DoctorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor / Paramedic.
        /// </summary>
        public static string DoctorOrParamedic {
            get {
                return ResourceManager.GetString("DoctorOrParamedic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor Registration Wizard.
        /// </summary>
        public static string DoctorRegistrationWizard {
            get {
                return ResourceManager.GetString("DoctorRegistrationWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor Type.
        /// </summary>
        public static string DoctorType {
            get {
                return ResourceManager.GetString("DoctorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Doctor Form.
        /// </summary>
        public static string EditDoctorForm {
            get {
                return ResourceManager.GetString("EditDoctorForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Paramedic Form.
        /// </summary>
        public static string EditParamedicForm {
            get {
                return ResourceManager.GetString("EditParamedicForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EmpEndDate {
            get {
                return ResourceManager.GetString("EmpEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        public static string EmpGrade {
            get {
                return ResourceManager.GetString("EmpGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emp ID.
        /// </summary>
        public static string EmpID {
            get {
                return ResourceManager.GetString("EmpID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Date.
        /// </summary>
        public static string EmpJoinDate {
            get {
                return ResourceManager.GetString("EmpJoinDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID.
        /// </summary>
        public static string EmployeeId {
            get {
                return ResourceManager.GetString("EmployeeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Info.
        /// </summary>
        public static string EmployeeInfo {
            get {
                return ResourceManager.GetString("EmployeeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee List.
        /// </summary>
        public static string EmployeeList {
            get {
                return ResourceManager.GetString("EmployeeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Type.
        /// </summary>
        public static string EmployeeType {
            get {
                return ResourceManager.GetString("EmployeeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation.
        /// </summary>
        public static string EmploymentType {
            get {
                return ResourceManager.GetString("EmploymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emp Reff.
        /// </summary>
        public static string EmpReffID {
            get {
                return ResourceManager.GetString("EmpReffID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emp Status.
        /// </summary>
        public static string EmpStatus {
            get {
                return ResourceManager.GetString("EmpStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your e-mail below and we will send you reset instructions!.
        /// </summary>
        public static string EnterEmailInstruction {
            get {
                return ResourceManager.GetString("EnterEmailInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Organization Code.
        /// </summary>
        public static string EnterOrganizationCode {
            get {
                return ResourceManager.GetString("EnterOrganizationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Username.
        /// </summary>
        public static string EnterUsername {
            get {
                return ResourceManager.GetString("EnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error .. !.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examine Glasses.
        /// </summary>
        public static string ExamineGlasses {
            get {
                return ResourceManager.GetString("ExamineGlasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired Date.
        /// </summary>
        public static string ExpiredDate {
            get {
                return ResourceManager.GetString("ExpiredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation.
        /// </summary>
        public static string FamilyRelationship {
            get {
                return ResourceManager.GetString("FamilyRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to finish this patient queue?.
        /// </summary>
        public static string FinishConfirmation {
            get {
                return ResourceManager.GetString("FinishConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password ?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password Page.
        /// </summary>
        public static string ForgotPasswordTitle {
            get {
                return ResourceManager.GetString("ForgotPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Medical.
        /// </summary>
        public static string FormMedical {
            get {
                return ResourceManager.GetString("FormMedical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Pre Examine.
        /// </summary>
        public static string FormPreExamine {
            get {
                return ResourceManager.GetString("FormPreExamine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold.
        /// </summary>
        public static string Hold {
            get {
                return ResourceManager.GetString("Hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to hold this patient queue ?.
        /// </summary>
        public static string HoldConfirmation {
            get {
                return ResourceManager.GetString("HoldConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medica System.
        /// </summary>
        public static string HomepageTitle {
            get {
                return ResourceManager.GetString("HomepageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No HP.
        /// </summary>
        public static string HPNumber {
            get {
                return ResourceManager.GetString("HPNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB Date.
        /// </summary>
        public static string KBDate {
            get {
                return ResourceManager.GetString("KBDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KTP No.
        /// </summary>
        public static string KTP {
            get {
                return ResourceManager.GetString("KTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KTP No.
        /// </summary>
        public static string KTPNumber {
            get {
                return ResourceManager.GetString("KTPNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Emp ID.
        /// </summary>
        public static string LastEmpID {
            get {
                return ResourceManager.GetString("LastEmpID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Eye.
        /// </summary>
        public static string LeftEye {
            get {
                return ResourceManager.GetString("LeftEye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Date.
        /// </summary>
        public static string LegalDate {
            get {
                return ResourceManager.GetString("LegalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal No.
        /// </summary>
        public static string LegalNO {
            get {
                return ResourceManager.GetString("LegalNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locket Out....
        /// </summary>
        public static string LockedOut {
            get {
                return ResourceManager.GetString("LockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Detail.
        /// </summary>
        public static string LogDetail {
            get {
                return ResourceManager.GetString("LogDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medica Login.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Viewer.
        /// </summary>
        public static string LogViewer {
            get {
                return ResourceManager.GetString("LogViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longtitude.
        /// </summary>
        public static string Longtitude {
            get {
                return ResourceManager.GetString("Longtitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital Status.
        /// </summary>
        public static string MaritalStatus {
            get {
                return ResourceManager.GetString("MaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menstrual Date.
        /// </summary>
        public static string MenstrualDate {
            get {
                return ResourceManager.GetString("MenstrualDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MR Number.
        /// </summary>
        public static string MRNumber {
            get {
                return ResourceManager.GetString("MRNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        public static string Navigation {
            get {
                return ResourceManager.GetString("Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessity.
        /// </summary>
        public static string Necessity {
            get {
                return ResourceManager.GetString("Necessity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Patient.
        /// </summary>
        public static string NewPatient {
            get {
                return ResourceManager.GetString("NewPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Value.
        /// </summary>
        public static string NewValue {
            get {
                return ResourceManager.GetString("NewValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidak Aktif.
        /// </summary>
        public static string NonActive {
            get {
                return ResourceManager.GetString("NonActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old MR Number.
        /// </summary>
        public static string OldMRNumber {
            get {
                return ResourceManager.GetString("OldMRNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Value.
        /// </summary>
        public static string OldValue {
            get {
                return ResourceManager.GetString("OldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Code.
        /// </summary>
        public static string OrganizationCode {
            get {
                return ResourceManager.GetString("OrganizationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization List.
        /// </summary>
        public static string OrganizationList {
            get {
                return ResourceManager.GetString("OrganizationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Name.
        /// </summary>
        public static string OrganizationName {
            get {
                return ResourceManager.GetString("OrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Privilege.
        /// </summary>
        public static string OrganizationPrivilege {
            get {
                return ResourceManager.GetString("OrganizationPrivilege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramedic.
        /// </summary>
        public static string Paramedic {
            get {
                return ResourceManager.GetString("Paramedic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramedic Info.
        /// </summary>
        public static string ParamedicInfo {
            get {
                return ResourceManager.GetString("ParamedicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramedic List.
        /// </summary>
        public static string ParamedicList {
            get {
                return ResourceManager.GetString("ParamedicList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramedic Registration Wizard.
        /// </summary>
        public static string ParamedicRegistrationWizard {
            get {
                return ResourceManager.GetString("ParamedicRegistrationWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramedic Type.
        /// </summary>
        public static string ParamedicType {
            get {
                return ResourceManager.GetString("ParamedicType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        public static string Patient {
            get {
                return ResourceManager.GetString("Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Pasien.
        /// </summary>
        public static string PatientList {
            get {
                return ResourceManager.GetString("PatientList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Name.
        /// </summary>
        public static string PatientName {
            get {
                return ResourceManager.GetString("PatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Type.
        /// </summary>
        public static string PatientType {
            get {
                return ResourceManager.GetString("PatientType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Type.
        /// </summary>
        public static string PaymentType {
            get {
                return ResourceManager.GetString("PaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poli.
        /// </summary>
        public static string Poli {
            get {
                return ResourceManager.GetString("Poli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poli From.
        /// </summary>
        public static string PoliFrom {
            get {
                return ResourceManager.GetString("PoliFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poli Name.
        /// </summary>
        public static string PoliName {
            get {
                return ResourceManager.GetString("PoliName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poli Schedule List.
        /// </summary>
        public static string PoliScheduleList {
            get {
                return ResourceManager.GetString("PoliScheduleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poli Schedule Master List.
        /// </summary>
        public static string PoliScheduleMasterList {
            get {
                return ResourceManager.GetString("PoliScheduleMasterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poli To.
        /// </summary>
        public static string PoliTo {
            get {
                return ResourceManager.GetString("PoliTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poli Type.
        /// </summary>
        public static string PoliType {
            get {
                return ResourceManager.GetString("PoliType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privilege.
        /// </summary>
        public static string Privilege {
            get {
                return ResourceManager.GetString("Privilege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privilege List.
        /// </summary>
        public static string PrivilegeList {
            get {
                return ResourceManager.GetString("PrivilegeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to process this patient queue?.
        /// </summary>
        public static string ProcessConfirmation {
            get {
                return ResourceManager.GetString("ProcessConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse.
        /// </summary>
        public static string Pulse {
            get {
                return ResourceManager.GetString("Pulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue Code.
        /// </summary>
        public static string QueueCode {
            get {
                return ResourceManager.GetString("QueueCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue Poli.
        /// </summary>
        public static string QueuePoli {
            get {
                return ResourceManager.GetString("QueuePoli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover Password.
        /// </summary>
        public static string RecoverPassword {
            get {
                return ResourceManager.GetString("RecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reff ID.
        /// </summary>
        public static string ReffID {
            get {
                return ResourceManager.GetString("ReffID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency Call Name.
        /// </summary>
        public static string ReffPerson {
            get {
                return ResourceManager.GetString("ReffPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency Phone No.
        /// </summary>
        public static string ReffPersonNo {
            get {
                return ResourceManager.GetString("ReffPersonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation.
        /// </summary>
        public static string ReffRelation {
            get {
                return ResourceManager.GetString("ReffRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Type.
        /// </summary>
        public static string RegisterType {
            get {
                return ResourceManager.GetString("RegisterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration List.
        /// </summary>
        public static string RegistrationList {
            get {
                return ResourceManager.GetString("RegistrationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string RegistrationStatus {
            get {
                return ResourceManager.GetString("RegistrationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Type.
        /// </summary>
        public static string RegistrationType {
            get {
                return ResourceManager.GetString("RegistrationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remembered ?.
        /// </summary>
        public static string RememberQuestion {
            get {
                return ResourceManager.GetString("RememberQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string Replace {
            get {
                return ResourceManager.GetString("Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reschedule.
        /// </summary>
        public static string Reschedule {
            get {
                return ResourceManager.GetString("Reschedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive schedule could not be rescheduled !.
        /// </summary>
        public static string RescheduleConfirmation {
            get {
                return ResourceManager.GetString("RescheduleConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password Page.
        /// </summary>
        public static string ResetPasswordTitle {
            get {
                return ResourceManager.GetString("ResetPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respiratory.
        /// </summary>
        public static string Respiratory {
            get {
                return ResourceManager.GetString("Respiratory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Eye.
        /// </summary>
        public static string RightEye {
            get {
                return ResourceManager.GetString("RightEye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Assignment.
        /// </summary>
        public static string RoleAssignment {
            get {
                return ResourceManager.GetString("RoleAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role List.
        /// </summary>
        public static string RoleList {
            get {
                return ResourceManager.GetString("RoleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Privilege.
        /// </summary>
        public static string RolePrivilege {
            get {
                return ResourceManager.GetString("RolePrivilege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Privilege.
        /// </summary>
        public static string SetPrivilege {
            get {
                return ResourceManager.GetString("SetPrivilege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Role Privilege.
        /// </summary>
        public static string SetRolePrivilege {
            get {
                return ResourceManager.GetString("SetRolePrivilege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        public static string SortNumber {
            get {
                return ResourceManager.GetString("SortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STR No.
        /// </summary>
        public static string STRNumber {
            get {
                return ResourceManager.GetString("STRNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Systolic.
        /// </summary>
        public static string Systolic {
            get {
                return ResourceManager.GetString("Systolic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperatur.
        /// </summary>
        public static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has been locked out, please try again later..
        /// </summary>
        public static string ThisAccountLocked {
            get {
                return ResourceManager.GetString("ThisAccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Date.
        /// </summary>
        public static string TransactionDate {
            get {
                return ResourceManager.GetString("TransactionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized Access .. !.
        /// </summary>
        public static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded Photo.
        /// </summary>
        public static string UploadedPhoto {
            get {
                return ResourceManager.GetString("UploadedPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Existing Data &amp; Go to Loket.
        /// </summary>
        public static string UseExistingGoLoket {
            get {
                return ResourceManager.GetString("UseExistingGoLoket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User List.
        /// </summary>
        public static string UserList {
            get {
                return ResourceManager.GetString("UserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid From.
        /// </summary>
        public static string ValidFrom {
            get {
                return ResourceManager.GetString("ValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid To.
        /// </summary>
        public static string ValidTo {
            get {
                return ResourceManager.GetString("ValidTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Poli List.
        /// </summary>
        public static string PoliList
        {
            get{
                return ResourceManager.GetString("PoliList", resourceCulture);
            }
        }
    }
}
